NAME = convert
FLAG = -Wall -Wextra -Werror -o
SRC = main.cpp Convert.cpp

all:
	@clang++ $(FLAG) $(NAME) $(SRC)
	@echo "\033[32mBuilt $(NAME).\033[0m"
clean:
	@/bin/rm -f $(NAME)
	@echo "\033[32mCleaned up compiled files.\033[0m"